addressing_7040 = {
    "data_points": [
        {"name": "External Shutdown",
         "address": 47,
         "type": "COIL"},
        {"name": "E-Stop Pressed",
         "address": 89,
         "type": "COIL"},
        {"name": "Manual Switch Position",
         "address": "3",
         "type": "bit"},
        {"name": "Auto Switch Position",
         "address": "3",
         "type": "bit"},
        {"name": "Vacuum Alarm",
         "address": 83,
         "type": "COIL"},
        {"name": "Pressure Alarm",
         "address": 84,
         "type": "COIL"},
        {"name": "PT1 High Pressure Alarm",
         "address": 37,
         "type": "COIL"},
        {"name": "Change Filter 1 Alarm",
         "address": 0,
         "type": "COIL"},
        {"name": "Change Filter 2 Alarm",
         "address": 0,
         "type": "COIL"},
        {"name": "No Flow Alarm",
         "address": 0,
         "type": "COIL"},
        {"name": "Leak Alarm",
         "address": 0,
         "type": "COIL"},
        {"name": "High Water Alarm",
         "address": 0,
         "type": "COIL"},
        {"name": "High Drum Alarm",
         "address": 0,
         "type": "COIL"},
        {"name": "Pump Overload Alarm",
         "address": 0,
         "type": "COIL"},
        {"name": "Tank 1 Supply Valve Alarm",
         "address": 0,
         "type": "COIL"},
        {"name": "Tank 2 Supply Valve Alarm",
         "address": 0,
         "type": "COIL"},
        {"name": "Tank 3 Supply Valve Alarm",
         "address": 0,
         "type": "COIL"},
        {"name": "Tank 4 Supply Valve Alarm",
         "address": 0,
         "type": "COIL"},
        {"name": "Tank 1 Return Valve Alarm",
         "address": 0,
         "type": "COIL"},
        {"name": "Tank 2 Return Valve Alarm",
         "address": 0,
         "type": "COIL"},
        {"name": "Tank 3 Return Valve Alarm",
         "address": 0,
         "type": "COIL"},
        {"name": "Tank 4 Return Valve Alarm",
         "address": 0,
         "type": "COIL"},
        {"name": "Tank 1 Overflow Alarm",
         "address": 0,
         "type": "COIL"},
        {"name": "Tank 2 Overflow Alarm",
         "address": 0,
         "type": "COIL"},
        {"name": "Tank 3 Overflow Alarm",
         "address": 0,
         "type": "COIL"},
        {"name": "Tank 4 Overflow Alarm",
         "address": 0,
         "type": "COIL"}
    ]
}

devices = {
    "7040": [
        {
            "ip": "192.168.0.59",
            "name": "Jacksonville"
        },
        {
            "ip": "192.168.0.59",
            "name": "Fort Worth"
        }
    ]
}